export const ACTION_STRING = {
  pending: "_PENDING",
  rejected: "_REJECTED",
  fulfilled: "_FULFILLED",
  authLogin: "AUTH_LOGIN",
  authLogout: "AUTH_LOGOUT",
  profile: "PROFILE",
  editImage: "EDIT_IMAGE",
  authRegister: "AUTH_REGISTER",
  authForgot: "AUTH_FORGOT",
  getUpcoming: "GET_UPCOMING",
  getShowing: "GET_SHOWING",
  getDetails: "GET_DETAILS",
  createMovie: "CREATE_MOVIE",
};
